# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/Admin/Desktop/github/3D-Graphics-Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/Admin/Desktop/github/3D-Graphics-Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/Admin/Desktop/github/3D-Graphics-Template/CMakeFiles C:/Users/Admin/Desktop/github/3D-Graphics-Template//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/Admin/Desktop/github/3D-Graphics-Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build.make _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glad-build/CMakeFiles/glad-generate-files.dir/build.make _deps/glad-build/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glad-build/CMakeFiles/glad.dir/build.make _deps/glad-build/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

_deps/imgui-src/backends/imgui_impl_glfw.obj: _deps/imgui-src/backends/imgui_impl_glfw.cpp.obj
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.obj

# target to build an object file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.obj
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.obj

_deps/imgui-src/backends/imgui_impl_glfw.i: _deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.i

_deps/imgui-src/backends/imgui_impl_glfw.s: _deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.s

_deps/imgui-src/backends/imgui_impl_opengl3.obj: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.obj
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.obj

# target to build an object file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.obj
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.obj

_deps/imgui-src/backends/imgui_impl_opengl3.i: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i

_deps/imgui-src/backends/imgui_impl_opengl3.s: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s

_deps/imgui-src/imgui.obj: _deps/imgui-src/imgui.cpp.obj
.PHONY : _deps/imgui-src/imgui.obj

# target to build an object file
_deps/imgui-src/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui.cpp.obj
.PHONY : _deps/imgui-src/imgui.cpp.obj

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.obj: _deps/imgui-src/imgui_demo.cpp.obj
.PHONY : _deps/imgui-src/imgui_demo.obj

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_demo.cpp.obj
.PHONY : _deps/imgui-src/imgui_demo.cpp.obj

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.obj: _deps/imgui-src/imgui_draw.cpp.obj
.PHONY : _deps/imgui-src/imgui_draw.obj

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_draw.cpp.obj
.PHONY : _deps/imgui-src/imgui_draw.cpp.obj

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.obj: _deps/imgui-src/imgui_tables.cpp.obj
.PHONY : _deps/imgui-src/imgui_tables.obj

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_tables.cpp.obj
.PHONY : _deps/imgui-src/imgui_tables.cpp.obj

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.obj: _deps/imgui-src/imgui_widgets.cpp.obj
.PHONY : _deps/imgui-src/imgui_widgets.obj

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_widgets.cpp.obj
.PHONY : _deps/imgui-src/imgui_widgets.cpp.obj

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

src/application.obj: src/application.cpp.obj
.PHONY : src/application.obj

# target to build an object file
src/application.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/application.cpp.obj
.PHONY : src/application.cpp.obj

src/application.i: src/application.cpp.i
.PHONY : src/application.i

# target to preprocess a source file
src/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/application.cpp.i
.PHONY : src/application.cpp.i

src/application.s: src/application.cpp.s
.PHONY : src/application.s

# target to generate assembly for a file
src/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/application.cpp.s
.PHONY : src/application.cpp.s

src/boundingBox.obj: src/boundingBox.cpp.obj
.PHONY : src/boundingBox.obj

# target to build an object file
src/boundingBox.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boundingBox.cpp.obj
.PHONY : src/boundingBox.cpp.obj

src/boundingBox.i: src/boundingBox.cpp.i
.PHONY : src/boundingBox.i

# target to preprocess a source file
src/boundingBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boundingBox.cpp.i
.PHONY : src/boundingBox.cpp.i

src/boundingBox.s: src/boundingBox.cpp.s
.PHONY : src/boundingBox.s

# target to generate assembly for a file
src/boundingBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boundingBox.cpp.s
.PHONY : src/boundingBox.cpp.s

src/camera.obj: src/camera.cpp.obj
.PHONY : src/camera.obj

# target to build an object file
src/camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.obj
.PHONY : src/camera.cpp.obj

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/crosshair.obj: src/crosshair.cpp.obj
.PHONY : src/crosshair.obj

# target to build an object file
src/crosshair.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/crosshair.cpp.obj
.PHONY : src/crosshair.cpp.obj

src/crosshair.i: src/crosshair.cpp.i
.PHONY : src/crosshair.i

# target to preprocess a source file
src/crosshair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/crosshair.cpp.i
.PHONY : src/crosshair.cpp.i

src/crosshair.s: src/crosshair.cpp.s
.PHONY : src/crosshair.s

# target to generate assembly for a file
src/crosshair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/crosshair.cpp.s
.PHONY : src/crosshair.cpp.s

src/exampleObject.obj: src/exampleObject.cpp.obj
.PHONY : src/exampleObject.obj

# target to build an object file
src/exampleObject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exampleObject.cpp.obj
.PHONY : src/exampleObject.cpp.obj

src/exampleObject.i: src/exampleObject.cpp.i
.PHONY : src/exampleObject.i

# target to preprocess a source file
src/exampleObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exampleObject.cpp.i
.PHONY : src/exampleObject.cpp.i

src/exampleObject.s: src/exampleObject.cpp.s
.PHONY : src/exampleObject.s

# target to generate assembly for a file
src/exampleObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exampleObject.cpp.s
.PHONY : src/exampleObject.cpp.s

src/grid.obj: src/grid.cpp.obj
.PHONY : src/grid.obj

# target to build an object file
src/grid.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/grid.cpp.obj
.PHONY : src/grid.cpp.obj

src/grid.i: src/grid.cpp.i
.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s
.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/interactive.obj: src/interactive.cpp.obj
.PHONY : src/interactive.obj

# target to build an object file
src/interactive.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/interactive.cpp.obj
.PHONY : src/interactive.cpp.obj

src/interactive.i: src/interactive.cpp.i
.PHONY : src/interactive.i

# target to preprocess a source file
src/interactive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/interactive.cpp.i
.PHONY : src/interactive.cpp.i

src/interactive.s: src/interactive.cpp.s
.PHONY : src/interactive.s

# target to generate assembly for a file
src/interactive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/interactive.cpp.s
.PHONY : src/interactive.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/object.obj: src/object.cpp.obj
.PHONY : src/object.obj

# target to build an object file
src/object.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/object.cpp.obj
.PHONY : src/object.cpp.obj

src/object.i: src/object.cpp.i
.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s
.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/renderable.obj: src/renderable.cpp.obj
.PHONY : src/renderable.obj

# target to build an object file
src/renderable.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/renderable.cpp.obj
.PHONY : src/renderable.cpp.obj

src/renderable.i: src/renderable.cpp.i
.PHONY : src/renderable.i

# target to preprocess a source file
src/renderable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/renderable.cpp.i
.PHONY : src/renderable.cpp.i

src/renderable.s: src/renderable.cpp.s
.PHONY : src/renderable.s

# target to generate assembly for a file
src/renderable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/renderable.cpp.s
.PHONY : src/renderable.cpp.s

src/shader.obj: src/shader.cpp.obj
.PHONY : src/shader.obj

# target to build an object file
src/shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.obj
.PHONY : src/shader.cpp.obj

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/shaderManager.obj: src/shaderManager.cpp.obj
.PHONY : src/shaderManager.obj

# target to build an object file
src/shaderManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shaderManager.cpp.obj
.PHONY : src/shaderManager.cpp.obj

src/shaderManager.i: src/shaderManager.cpp.i
.PHONY : src/shaderManager.i

# target to preprocess a source file
src/shaderManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shaderManager.cpp.i
.PHONY : src/shaderManager.cpp.i

src/shaderManager.s: src/shaderManager.cpp.s
.PHONY : src/shaderManager.s

# target to generate assembly for a file
src/shaderManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shaderManager.cpp.s
.PHONY : src/shaderManager.cpp.s

src/textmanager.obj: src/textmanager.cpp.obj
.PHONY : src/textmanager.obj

# target to build an object file
src/textmanager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/textmanager.cpp.obj
.PHONY : src/textmanager.cpp.obj

src/textmanager.i: src/textmanager.cpp.i
.PHONY : src/textmanager.i

# target to preprocess a source file
src/textmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/textmanager.cpp.i
.PHONY : src/textmanager.cpp.i

src/textmanager.s: src/textmanager.cpp.s
.PHONY : src/textmanager.s

# target to generate assembly for a file
src/textmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/textmanager.cpp.s
.PHONY : src/textmanager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glad-generate-files"
	@echo "... update_mappings"
	@echo "... glad"
	@echo "... glfw"
	@echo "... glm"
	@echo "... main"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.obj"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.obj"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.s"
	@echo "... _deps/imgui-src/imgui.obj"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.obj"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.obj"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.obj"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.obj"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... src/application.obj"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/boundingBox.obj"
	@echo "... src/boundingBox.i"
	@echo "... src/boundingBox.s"
	@echo "... src/camera.obj"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/crosshair.obj"
	@echo "... src/crosshair.i"
	@echo "... src/crosshair.s"
	@echo "... src/exampleObject.obj"
	@echo "... src/exampleObject.i"
	@echo "... src/exampleObject.s"
	@echo "... src/grid.obj"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/interactive.obj"
	@echo "... src/interactive.i"
	@echo "... src/interactive.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/object.obj"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/renderable.obj"
	@echo "... src/renderable.i"
	@echo "... src/renderable.s"
	@echo "... src/shader.obj"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/shaderManager.obj"
	@echo "... src/shaderManager.i"
	@echo "... src/shaderManager.s"
	@echo "... src/textmanager.obj"
	@echo "... src/textmanager.i"
	@echo "... src/textmanager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

